import { AnalysisResult } from '../types';

export const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
};

export const generateMarkdownExport = (data: AnalysisResult): string => {
  let md = `# ${data.metadata.title}\n`;
  md += `**Subject:** ${data.metadata.subject} | **Study Time:** ${data.metadata.estimatedStudyTime} | **Level:** ${data.explanationLevel.toUpperCase()}\n\n`;
  md += `> "Turn your study material into your personal exam strategy." — Generated by NoteGen AI\n\n`;
  md += `---\n\n`;

  // Summary
  md += `## 1. Quick Summary\n\n${data.summary.quickSummary}\n\n`;
  md += `**Key Takeaway:** ${data.summary.keyTakeaway}\n\n`;
  md += `**Core Premise:** ${data.summary.corePremise}\n\n`;
  md += `---\n\n`;

  // Key Points
  md += `## 2. Key Points\n\n`;
  data.keyPoints.forEach((kp, idx) => {
    md += `${idx + 1}. **[${kp.importance}]** ${kp.point} *(${kp.category})*\n`;
  });
  md += `\n---\n\n`;

  // Topic-wise notes
  md += `## 3. Topic-wise Detailed Notes\n\n`;
  data.topicNotes.forEach((topic) => {
    md += `### ${topic.topicTitle} (Yield: ${topic.examYield})\n`;
    md += `*Source Reference: ${topic.sourceReference}*\n\n`;
    md += `${topic.simpleExplanation}\n\n`;

    if (topic.importantConcepts && topic.importantConcepts.length > 0) {
      md += `**Important Concepts:**\n`;
      topic.importantConcepts.forEach((c) => (md += `- ${c}\n`));
      md += `\n`;
    }

    if (topic.definitions && topic.definitions.length > 0) {
      md += `**Definitions:**\n`;
      topic.definitions.forEach((d) => (md += `- **${d.term}** → ${d.explanation}\n`));
      md += `\n`;
    }

    if (topic.examples && topic.examples.length > 0) {
      md += `**Examples in Source:**\n`;
      topic.examples.forEach((ex) => (md += `- ${ex}\n`));
      md += `\n`;
    }

    if (topic.commonMistake) {
      md += `> ⚠️ **Common Exam Mistake:** ${topic.commonMistake}\n\n`;
    }
  });
  md += `---\n\n`;

  // Definitions
  md += `## 4. Important Definitions\n\n`;
  data.definitions.forEach((d) => {
    md += `- **${d.term}** → ${d.explanation}\n`;
  });
  md += `\n---\n\n`;

  // Formulas
  md += `## 5. Important Formulas\n\n`;
  if (data.hasFormulas && data.formulas.length > 0) {
    data.formulas.forEach((f) => {
      md += `### ${f.name}\n`;
      md += `\`\`\`\n${f.formula}\n\`\`\`\n`;
      md += `**Explanation:** ${f.explanation}\n`;
      if (f.variables && f.variables.length > 0) {
        md += `**Variables:**\n`;
        f.variables.forEach((v) => (md += `- ${v}\n`));
      }
      md += `*Context: ${f.sourceContext}*\n\n`;
    });
  } else {
    md += `*${data.formulasNote || 'No mathematical formulas found in this source.'}*\n\n`;
  }
  md += `---\n\n`;

  // Exam Revision Points
  md += `## 6. Exam Revision Points\n\n`;
  md += `*(High-yield revision points based on source material analysis; not guaranteed exam leaks.)*\n\n`;
  data.examRevisionPoints.forEach((rp, idx) => {
    md += `- [${rp.priority}] **${rp.category}:** ${rp.point}\n`;
  });
  md += `\n---\n\n`;

  // Prioritization
  md += `## 7. Exam Strategy & Prioritization Matrix\n\n`;
  md += `${data.prioritizationMatrix.focusSummary}\n\n`;
  md += `### Time Allocation Guide:\n`;
  data.prioritizationMatrix.timeAllocationAdvice.forEach((ta) => {
    md += `- **${ta.topic} (${ta.percentage}% of study time):** ${ta.rationale}\n`;
  });
  md += `\n### Examiner Traps to Avoid:\n`;
  data.prioritizationMatrix.examinerPitfalls.forEach((ep) => {
    md += `- **${ep.topic}:** ${ep.trap} *(Solution: ${ep.howToAvoid})*\n`;
  });

  return md;
};

export const downloadTextFile = (content: string, filename: string, mimeType = 'text/markdown') => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
