import { SampleMaterial } from '../types';

export const SAMPLE_MATERIALS: SampleMaterial[] = [
  {
    id: 'os-virtual-memory',
    title: 'Operating Systems: Virtual Memory & Page Replacement',
    subject: 'Computer Science & Engineering',
    tag: 'CS301 / Systems',
    description: 'Virtual address translation, Page Tables, TLB hit ratios, Page Fault handling, and FIFO vs LRU algorithms.',
    iconName: 'Cpu',
    content: `COURSE: CS 301 - Operating Systems Architecture
LECTURE 14: Virtual Memory Management, Paging, and Page Replacement Algorithms

1. OVERVIEW AND MOTIVATION
Virtual memory is a memory management technique that provides an "idealized abstraction of the storage resources that are actually available on a given machine" which creates the illusion to users of a very large (main) memory.
Key benefits:
- Separation of user logical memory from physical memory.
- Only parts of the program need to be in memory for execution.
- Logical address space can therefore be much larger than physical address space.
- Allows address spaces to be shared by several processes.
- Allows for more efficient process creation.

2. HARDWARE ARCHITECTURE & ADDRESS TRANSLATION
Every address generated by the CPU is divided into two parts:
- Page number (p): used as an index into a page table which contains base address of each page in physical memory.
- Page offset (d): combined with base address to define the physical memory address that is sent to the memory unit.
If the size of logical address space is 2^m, and a page size is 2^n bytes, then the high-order m-n bits of a logical address designate the page number, and the n low-order bits designate the page offset.

Translation Lookaside Buffer (TLB):
A special, small, fast-lookup hardware cache consisting of associative, high-speed memory.
Each entry consists of a key (tag) and a value.
When a logical address is generated, its page number is presented to the TLB. If found (TLB Hit), the frame number is immediately available.
If the page number is not in the TLB (TLB Miss), a memory reference to the page table must be made.

Mathematical Formula for Effective Access Time (EAT):
Let hit_ratio be alpha (percentage of times that a page number is found in TLB).
Let memory access time be m (typically 100 ns).
Let TLB lookup time be epsilon (typically 20 ns).
Formula:
EAT = (m + epsilon) * alpha + (2m + epsilon) * (1 - alpha)
Simplified: EAT = (2 - alpha) * m + epsilon
Where:
- alpha: TLB hit ratio (between 0.0 and 1.0)
- m: Main memory cycle access time
- epsilon: TLB search overhead time

3. PAGE FAULT HANDLING WORKFLOW
A page fault occurs when an access to a page that is marked invalid (not currently loaded into a physical RAM frame) is executed.
Step-by-step handler sequence:
Step 1: Operating system traps to kernel mode when hardware detects invalid bit in page table entry.
Step 2: Save user registers and process state.
Step 3: Determine whether internal reference was invalid address or simply page not yet brought into memory.
Step 4: Find a free frame from physical memory's free-frame list.
Step 5: Issue disk I/O read operation to bring desired page from backing store into allocated frame.
Step 6: While waiting for I/O completion, CPU may be allocated to other processes (context switch).
Step 7: Disk interrupt arrives indicating I/O transfer complete.
Step 8: Update internal table and page table entry to reflect that page is now in RAM with valid bit set to 1.
Step 9: Restart the instruction that was interrupted by the page fault trap.

4. PAGE REPLACEMENT ALGORITHMS
When no frame is free in physical memory, the OS must swap out a victim page to swap space.
- First-In, First-Out (FIFO): The oldest page brought into memory is selected as victim. Subject to Belady's Anomaly (for some page-replacement algorithms, the page-fault rate may increase as the number of allocated frames increases).
- Optimal Algorithm (OPT / MIN): Replace the page that will not be used for the longest period of time. Guarantees lowest possible page fault rate, but impossible to implement in practice because it requires future knowledge. Used as a benchmark.
- Least Recently Used (LRU): Replaces the page that has not been used for the longest period of time. Approximates OPT by looking backward in time rather than forward. Implemented using counters or stack. Does NOT suffer from Belady's Anomaly (it is a stack algorithm).
- Clock / Second-Chance Algorithm: FIFO replacement with a reference bit (0 or 1). If reference bit is 0, replace page. If 1, set bit to 0, advance clock hand, giving page a second chance.

5. EXAM PITFALLS & HIGH-YIELD POINTS
- Students frequently confuse Belady's Anomaly: Remember that FIFO exhibits Belady's Anomaly, while LRU and Optimal NEVER exhibit it because they satisfy the inclusion property.
- When calculating EAT, do not forget the 2 memory accesses on a TLB miss: one access to read the page table entry, and the second access to retrieve the actual data/instruction from RAM.`
  },
  {
    id: 'bio-cellular-respiration',
    title: 'Biochemistry: Cellular Respiration & ATP Synthase',
    subject: 'Biology & Biochemistry',
    tag: 'BIO204 / Cell Biology',
    description: 'Glycolysis, Pyruvate oxidation, Citric Acid (Krebs) cycle, Electron Transport Chain, and Chemiosmosis.',
    iconName: 'Dna',
    content: `COURSE: BIO 204 - Cell Biology & Metabolic Pathways
LECTURE 8: Cellular Respiration, Oxidative Phosphorylation, and ATP Synthase

1. CENTRAL METABOLIC EQUATION & OVERVIEW
Cellular respiration is the set of metabolic reactions and processes that take place in the cells of organisms to convert biochemical energy from nutrients into adenosine triphosphate (ATP), and then release waste products.

Overall Balanced Chemical Reaction:
C6H12O6 + 6 O2 -> 6 CO2 + 6 H2O + ~30-32 ATP + Heat

2. FOUR DISTINCT STAGES
Stage 1: Glycolysis (Cytoplasm)
- Degradation of 1 glucose (6-carbon molecule) into 2 molecules of pyruvate (3 carbons each).
- Anaerobic: does not require molecular oxygen.
- Energy Investment Phase: Consumes 2 ATP molecules to phosphorylate glucose (hexokinase & phosphofructokinase-1).
- Energy Payoff Phase: Produces 4 ATP via substrate-level phosphorylation and 2 NADH molecules.
- Net Yield: 2 ATP + 2 NADH + 2 Pyruvate.

Stage 2: Pyruvate Oxidation / Link Reaction (Mitochondrial Matrix)
- Each pyruvate enters mitochondrial matrix via pyruvate translocase symporter.
- Pyruvate dehydrogenase multienzyme complex (PDH) catalyzes oxidative decarboxylation:
  Pyruvate + NAD+ + CoA-SH -> Acetyl-CoA + NADH + CO2 + H+
- For one glucose molecule (2 pyruvates): Produces 2 Acetyl-CoA + 2 NADH + 2 CO2.

Stage 3: The Citric Acid (Krebs / TCA) Cycle (Mitochondrial Matrix)
- Acetyl-CoA (2C) combines with Oxaloacetate (4C) via citrate synthase to form Citrate (6C).
- Each turn of the cycle undergoes two decarboxylation steps, yielding:
  - 3 NADH
  - 1 FADH2
  - 1 GTP (convertible to ATP via nucleoside diphosphate kinase)
  - 2 CO2 released as metabolic waste
- For one original glucose (2 turns): 6 NADH, 2 FADH2, 2 ATP/GTP, 4 CO2.

Stage 4: Oxidative Phosphorylation (Inner Mitochondrial Membrane)
Consists of two coupled components:
A. Electron Transport Chain (ETC):
- Complexes I, II, III, and IV embedded in the inner mitochondrial membrane (cristae).
- High energy electrons from NADH (entering at Complex I) and FADH2 (entering at Complex II) are passed down redox potential gradient to terminal electron acceptor O2, producing H2O.
- Electron transfer drives proton pumping from matrix across inner membrane into intermembrane space (Complex I, III, IV pump H+).
- Creates an electrochemical proton gradient (Proton-Motive Force, PMF), with high [H+] and positive voltage in intermembrane space.

B. Chemiosmosis & ATP Synthase (F0F1 complex):
- Protons flow down their steep electrochemical gradient back into mitochondrial matrix through F0 subunit rotor of ATP Synthase.
- Flow causes rotation of gamma subunit shaft, inducing conformational changes in catalytic beta subunits of F1 headpiece (Open, Loose, Tight states - Paul Boyer's Binding Mechanism).
- Phosphorylation of ADP + Pi -> ATP.
- P/O Ratio: 1 NADH produces approximately 2.5 ATP; 1 FADH2 produces approximately 1.5 ATP.

3. INHIBITORS & UNCOUPLERS (FREQUENT EXAM TOPIC)
- Cyanide (CN-) and Carbon Monoxide (CO): Inhibit Cytochrome c Oxidase (Complex IV), blocking electron flow and halting proton pumping and ATP production.
- Oligomycin: Directly binds F0 stalk of ATP Synthase, blocking proton channel and halting ATP synthesis (causes proton gradient to build up until ETC stops).
- 2,4-Dinitrophenol (DNP) & Thermogenin (UCP-1 in brown fat): Chemical uncouplers that carry protons across membrane without passing through ATP Synthase. Electron transport continues rapidly, O2 consumption skyrockets, but no ATP is synthesized; energy is dissipated entirely as heat.

4. EXAM REVISION SUMMARY
- Glycolysis occurs in cytoplasm; Krebs and ETC occur inside mitochondria.
- Total net ATP yield per mole of glucose oxidized: 30 to 32 ATP under aerobic conditions.
- DNP uncouples ETC from ATP synthase: ETC runs, oxygen used, but zero ATP produced (100% heat).`
  },
  {
    id: 'physics-electromagnetism',
    title: 'Physics: Electromagnetic Induction & Maxwell’s Equations',
    subject: 'Physics & Electrical Engineering',
    tag: 'PHYS212 / Electromagnetism',
    description: 'Faraday’s Law, Lenz’s Law, Motional EMF, Mutual & Self-Inductance, and Maxwell’s four unified field equations.',
    iconName: 'Zap',
    content: `COURSE: PHYS 212 - Electricity & Magnetism
LECTURE 18: Faraday's Law of Induction, Lenz's Law, and Maxwell's Equations

1. MAGNETIC FLUX (Phi_B)
Magnetic flux measures the total magnetic field passing through a specified surface area A.
Formula:
Phi_B = integral(B * dA) = B * A * cos(theta)
Units: Weber (Wb) = Tesla * meter^2 (T * m^2)
Where:
- B is magnetic flux density vector
- A is area vector normal to surface
- theta is angle between B and normal vector n

2. FARADAY'S LAW OF INDUCTION
Any change in the magnetic environment of a coil of wire will cause a voltage (electromotive force, EMF, denoted epsilon) to be induced in the coil.
Formula:
epsilon = -N * (dPhi_B / dt)
Where:
- epsilon is the induced electromotive force (volts)
- N is the number of turns in the loop or coil
- dPhi_B / dt is the time rate of change of magnetic flux
The negative sign expresses Lenz's Law: The direction of the induced current is always such that its own magnetic field opposes the original change in magnetic flux that produced it.

3. MOTIONAL ELECTROMOTIVE FORCE
When a conducting rod of length L moves at constant velocity v perpendicular to a uniform magnetic field B:
Motional EMF:
epsilon = B * L * v
Induced Current through loop with resistance R:
I = epsilon / R = (B * L * v) / R
Magnetic Retarding Force:
F_B = I * L * B = (B^2 * L^2 * v) / R
Mechanical Power required to pull rod equals electrical power dissipated in resistor:
P_mech = F * v = (B^2 * L^2 * v^2) / R = I^2 * R = P_elec

4. SELF-INDUCTANCE AND ENERGY DENSITY
Inductance L relates magnetic flux linkage to current:
N * Phi_B = L * I
Induced Back-EMF in inductor:
epsilon_L = -L * (dI / dt)
Magnetic Energy stored in an Inductor:
U_B = (1/2) * L * I^2
Energy Density of Magnetic Field in vacuum:
u_B = B^2 / (2 * mu_0)
Where mu_0 = 4 * pi * 10^-7 T*m/A is vacuum permeability.

5. MAXWELL'S FOUR UNIFIED EQUATIONS
In integral form (free space):
1. Gauss's Law for Electricity:
   integral(E * dA) = Q_enclosed / epsilon_0
   Physical Meaning: Electric charges are sources and sinks of electric fields.
2. Gauss's Law for Magnetism:
   integral(B * dA) = 0
   Physical Meaning: No isolated magnetic monopoles exist; magnetic field lines form continuous closed loops.
3. Faraday's Law of Induction:
   integral(E * ds) = - d(Phi_B) / dt
   Physical Meaning: A changing magnetic flux creates a circulating electric field.
4. Ampere-Maxwell Law:
   integral(B * ds) = mu_0 * I_enclosed + mu_0 * epsilon_0 * (dPhi_E / dt)
   Where I_d = epsilon_0 * (dPhi_E / dt) is Maxwell's Displacement Current.
   Physical Meaning: Magnetic fields are produced both by moving electric currents and by time-varying electric fields.

6. HIGH YIELD EXAM CHECKLIST
- A constant magnetic field NEVER induces an EMF; flux must change with respect to time (dPhi/dt != 0).
- Maxwell added the displacement current term (dPhi_E/dt) to fix Ampere's law for charging capacitors and satisfy charge continuity.
- In motional EMF problems, always apply Lenz's rule and right-hand rule to verify the direction of induced current.`
  },
  {
    id: 'finance-capital-budgeting',
    title: 'Finance: Capital Budgeting & Investment Decision Rules',
    subject: 'Economics & Corporate Finance',
    tag: 'FIN401 / Corporate Finance',
    description: 'Net Present Value (NPV), Internal Rate of Return (IRR), Payback Period, Profitability Index, and WACC hurdle rates.',
    iconName: 'TrendingUp',
    content: `COURSE: FIN 401 - Corporate Financial Management
LECTURE 6: Capital Budgeting Principles, Valuation Models, and Decision Rules

1. FUNDAMENTALS OF CAPITAL BUDGETING
Capital budgeting is the process a business uses to evaluate potential major projects or investments.
Fundamental rule of corporate value creation: Invest only in assets that earn a return greater than the opportunity cost of capital (WACC).

2. NET PRESENT VALUE (NPV) - THE GOLD STANDARD
Net Present Value calculates the present value of all expected future cash inflows minus the initial investment outlay.
Mathematical Formula:
NPV = sum_{t=1}^T [ CF_t / (1 + r)^t ] - CF_0
Where:
- CF_0 = Initial capital outlay at time t = 0
- CF_t = Net after-tax cash flow at period t
- r = Discount rate / Cost of capital (WACC)
- T = Total project economic lifespan
Decision Rule:
- Accept project if NPV > 0 (creates shareholder value).
- Reject project if NPV < 0 (destroys value).
- Between mutually exclusive projects: Choose project with highest positive NPV.

3. INTERNAL RATE OF RETURN (IRR)
The discount rate that forces the NPV of a project to exactly equal zero.
Mathematical Definition:
0 = sum_{t=1}^T [ CF_t / (1 + IRR)^t ] - CF_0
Decision Rule:
- Accept project if IRR > Cost of Capital (r / WACC).
- Reject project if IRR < Cost of Capital.
Critical Limitations & Pitfalls of IRR:
- Multiple IRRs: If project cash flows change sign more than once (non-conventional cash flows, e.g. - + -), there can be multiple internal rates of return (Descartes' Rule of Signs).
- Scale Problem: IRR ignores investment size. A 100% return on $10 creates far less wealth than a 25% return on $1,000,000.
- Reinvestment Rate Assumption: IRR assumes intermediate cash flows are reinvested at the IRR itself (unrealistic). NPV assumes reinvestment at the cost of capital (realistic).

4. PROFITABILITY INDEX (PI)
Ratio of present value of future cash flows to initial outlay:
PI = PV of Future Cash Inflows / Initial Outlay = (sum_{t=1}^T [ CF_t / (1 + r)^t ]) / CF_0
Decision Rule:
- Accept if PI > 1.0.
- Exceptionally useful under capital rationing (limited investment budget).

5. WEIGHTED AVERAGE COST OF CAPITAL (WACC)
The minimum hurdle rate required by all capital providers (equity and debt):
Formula:
WACC = (E / V) * Re + (D / V) * Rd * (1 - Tc)
Where:
- E = Market value of equity
- D = Market value of debt
- V = E + D (Total firm value)
- Re = Cost of equity (from CAPM: Re = Rf + beta * (Rm - Rf))
- Rd = Pre-tax cost of debt
- Tc = Corporate marginal tax rate (interest payments are tax-deductible)

6. EXAM PITFALLS & STRATEGY
- When NPV and IRR conflict for mutually exclusive projects: ALWAYS choose the project based on NPV. NPV directly measures absolute wealth added to shareholders.
- Sunk Costs must ALWAYS be excluded from cash flow forecasts (e.g. past R&D expense).
- Opportunity Costs must ALWAYS be included (e.g. using existing company land for a new facility).`
  }
];
